server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/eco_agua_prod?useSSL=false&serverTimezone=America/Limaspring.datasource.username=eco_user
spring.datasource.password=***MASKED***
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
logging.level.com.ecoamazonas.eco_agua=INFO

# Hide stacktraces in prod
server.error.include-message=never
server.error.include-stacktrace=never