-- Blog content seed for Productos de la Selva Belen
-- Generated for eco-agua / productos_selva_belen
SET NAMES utf8mb4;
SET time_zone = '+00:00';
USE `productos_selva_belen`;

-- This script inserts or updates blog articles by slug.
-- Copy images from uploads/belen/blog/ to your project uploads/belen/blog/ before testing the portal.

-- Article 1: Cómo conservar paiche seco y pescado ahumado en casa
INSERT INTO `blog_post` (`title`, `slug`, `summary`, `content`, `cover_image_path`, `status`, `created_at`, `published_at`) VALUES
('Cómo conservar paiche seco y pescado ahumado en casa', 'como-conservar-paiche-seco-y-pescado-ahumado', 'Guía práctica para guardar paiche seco, pescado seco y ahumados sin perder sabor, aroma ni calidad.', '
<h2>Conservar bien también es cuidar el sabor</h2>
<p>El paiche seco, el pescado seco y los ahumados son productos muy valorados en la cocina amazónica porque concentran sabor y ayudan a preparar comidas con identidad regional. Pero, como todo producto alimenticio, necesitan guardarse correctamente para evitar humedad, olores extraños o pérdida de textura.</p>
<p>En una ciudad cálida como Iquitos, el principal enemigo de estos productos es la humedad. Por eso, después de comprar, lo mejor es separar lo que se va a usar pronto y guardar el resto en bolsas limpias, envases cerrados o recipientes herméticos.</p>
<p style="background:#ecfdf5;border-left:4px solid #16a34a;padding:12px 14px;border-radius:10px;margin:16px 0;"><strong>Nota:</strong> La disponibilidad puede variar por temporada. Antes de comprar por cantidad, confirma stock y presentación por WhatsApp.</p>
<h2>Tabla rápida de conservación</h2>
<div style="overflow-x:auto;margin:16px 0;"><table style="width:100%;border-collapse:collapse;font-size:15px;"><thead><tr><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Producto</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Cómo guardarlo</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Tiempo referencial</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Señales de alerta</th></tr></thead><tbody><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Paiche seco</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">En bolsa bien cerrada o recipiente hermético, lejos de humedad y calor directo.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">1 a 3 semanas, según clima y presentación.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Olor agrio, moho, humedad visible o textura pegajosa.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Pescado ahumado</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Refrigerado si ya fue abierto; si está bien seco, en lugar fresco y ventilado.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">5 a 10 días como referencia.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Olor demasiado fuerte, superficie babosa o cambio raro de color.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Cecina y ahumados</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">En bolsa limpia, envase cerrado o refrigerado después de abrir.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">5 a 7 días como referencia.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Olor desagradable, humedad excesiva o color no habitual.</td></tr></tbody></table></div>
<h2>Errores comunes que debes evitar</h2>
<ul><li>Dejar el producto destapado sobre la mesa por muchas horas.</li><li>Guardarlo cerca de la cocina, horno o lugares calientes.</li><li>Mezclarlo con productos de olores muy fuertes.</li><li>Refrigerarlo sin bolsa o sin recipiente cerrado.</li><li>Comprar mucha cantidad sin tener un lugar adecuado para conservarlo.</li></ul>
<div style="background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Checklist rápido</h3><ul style="margin-bottom:0;list-style:none;padding-left:0;"><li style="margin-bottom:8px;">✅ Guardar en lugar fresco, limpio y seco.</li><li style="margin-bottom:8px;">✅ Separar porciones si compras para varios días.</li><li style="margin-bottom:8px;">✅ Revisar olor y textura antes de cocinar.</li><li style="margin-bottom:8px;">✅ Consultar presentación y disponibilidad antes de comprar por cantidad.</li></ul></div>
<h2>¿Cómo saber si está en buen estado?</h2>
<p>Un producto bien conservado mantiene olor natural, textura firme y apariencia estable. Si notas humedad extraña, manchas, moho, olor agrio o textura pegajosa, es mejor no consumirlo. La seguridad siempre debe estar por encima del ahorro.</p>
<div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Nivel recomendado</h3><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Lugar seco y ventilado</strong><span>95%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:95%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Recipiente cerrado</strong><span>90%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:90%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Exposición al sol</strong><span>15%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:15%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Humedad constante</strong><span>10%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:10%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div></div>
<h2>Conclusión</h2>
<p>El paiche seco y los pescados ahumados pueden durar más y conservar mejor su sabor si se almacenan con cuidado. Comprar la cantidad adecuada, confirmar presentación y protegerlos de la humedad hará que aproveches mejor cada pedido.</p>
<div style="background:#0f766e;color:#fff;padding:18px;border-radius:14px;margin-top:22px;"><h3 style="margin-top:0;color:#fff;">Consulta por WhatsApp</h3><p style="margin-bottom:0;">Consulta disponibilidad, presentación y precio actualizado por WhatsApp. Te respondemos según stock real y coordinación de entrega.</p></div>
', '/uploads/belen/blog/01-paiche-seco-pescado-ahumado.jpg', 'PUBLISHED', '2026-05-28 20:30:00', '2026-05-28 20:30:00')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `summary` = VALUES(`summary`),
  `content` = VALUES(`content`),
  `cover_image_path` = VALUES(`cover_image_path`),
  `status` = VALUES(`status`),
  `published_at` = VALUES(`published_at`);

-- Article 2: Hoja de bijao y hoja de plátano: cuándo usar cada una
INSERT INTO `blog_post` (`title`, `slug`, `summary`, `content`, `cover_image_path`, `status`, `created_at`, `published_at`) VALUES
('Hoja de bijao y hoja de plátano: cuándo usar cada una', 'hoja-de-bijao-y-hoja-de-platano-cuando-usar-cada-una', 'Comparativa simple para elegir la hoja adecuada según aroma, resistencia, tamaño y tipo de preparación.', '
<h2>Dos hojas importantes en la cocina amazónica</h2>
<p>La hoja de bijao y la hoja de plátano se usan para envolver, proteger y dar presentación a comidas tradicionales. Aunque a veces se confunden, no son iguales. Cada una tiene textura, aroma y resistencia diferente.</p>
<p>Si vas a preparar juanes, tamales, pescados envueltos o comidas para vender, elegir la hoja correcta puede mejorar el resultado final y evitar que la envoltura se rompa durante la preparación.</p>
<p style="background:#ecfdf5;border-left:4px solid #16a34a;padding:12px 14px;border-radius:10px;margin:16px 0;"><strong>Nota:</strong> La disponibilidad puede variar por temporada. Antes de comprar por cantidad, confirma stock y presentación por WhatsApp.</p>
<h2>Diferencias principales</h2>
<div style="overflow-x:auto;margin:16px 0;"><table style="width:100%;border-collapse:collapse;font-size:15px;"><thead><tr><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Característica</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Hoja de bijao</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Hoja de plátano</th></tr></thead><tbody><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Aroma</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Más aromática, ideal para preparaciones tradicionales.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Más neutra, acompaña sin dominar el sabor.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Resistencia</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Firme y buena para envolver porciones definidas.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Buena para envolver piezas más grandes, pero puede rasgarse si está seca.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Tamaño</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Mediano, práctico para juanes y envolturas.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Grande, útil para cubrir, envolver o cocinar al vapor.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Uso común</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Juanes, tamales, envueltos amazónicos.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Asados, vapor, presentaciones amplias y envolturas grandes.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Presentación</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Suele venderse por paquetes o atados.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Puede venderse por hojas, paquetes o atados.</td></tr></tbody></table></div>
<h2>¿Cuándo conviene usar hoja de bijao?</h2>
<ul><li>Cuando buscas aroma tradicional.</li><li>Cuando prepararás juanes o comidas típicas amazónicas.</li><li>Cuando necesitas una hoja firme para envolver porciones medianas.</li><li>Cuando quieres una presentación más típica y reconocible.</li></ul>
<h2>¿Cuándo conviene usar hoja de plátano?</h2>
<ul><li>Cuando necesitas cubrir una porción grande.</li><li>Cuando prepararás alimentos al vapor o a la parrilla.</li><li>Cuando buscas una hoja amplia y flexible.</li><li>Cuando quieres usarla también como base de presentación.</li></ul>
<div style="background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Checklist rápido</h3><ul style="margin-bottom:0;list-style:none;padding-left:0;"><li style="margin-bottom:8px;">✅ Lavar suavemente antes de usar.</li><li style="margin-bottom:8px;">✅ Secar con paño limpio.</li><li style="margin-bottom:8px;">✅ Pasar ligeramente por calor si está muy rígida.</li><li style="margin-bottom:8px;">✅ Guardar protegida para que no se reseque.</li></ul></div>
<h2>Consejo para negocios de comida</h2>
<p>Si tienes restaurante, puesto o negocio de comida, conviene consultar con anticipación la cantidad que necesitas. En fechas fuertes, como San Juan, la demanda de hojas puede subir y la disponibilidad puede cambiar rápido.</p>
<div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Nivel recomendado</h3><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Preparaciones tradicionales</strong><span>95%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:95%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Pedidos por temporada</strong><span>85%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:85%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Uso decorativo</strong><span>70%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:70%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Uso si está seca o rota</strong><span>20%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:20%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div></div>
<h2>Conclusión</h2>
<p>La hoja de bijao y la hoja de plátano no compiten: se complementan. La mejor elección depende del plato, la cantidad, la presentación y el aroma que quieres lograr.</p>
<div style="background:#0f766e;color:#fff;padding:18px;border-radius:14px;margin-top:22px;"><h3 style="margin-top:0;color:#fff;">Consulta por WhatsApp</h3><p style="margin-bottom:0;">Consulta disponibilidad de hojas de bijao y hojas de plátano por WhatsApp. Te confirmamos presentación, cantidad y coordinación según stock.</p></div>
', '/uploads/belen/blog/02-hojas-bijao-platano.jpg', 'PUBLISHED', '2026-05-28 20:30:00', '2026-05-28 20:30:00')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `summary` = VALUES(`summary`),
  `content` = VALUES(`content`),
  `cover_image_path` = VALUES(`cover_image_path`),
  `status` = VALUES(`status`),
  `published_at` = VALUES(`published_at`);

-- Article 3: Cómo comprar por mayor sin complicarte
INSERT INTO `blog_post` (`title`, `slug`, `summary`, `content`, `cover_image_path`, `status`, `created_at`, `published_at`) VALUES
('Cómo comprar por mayor sin complicarte', 'como-consultar-precios-por-mayor-sin-complicarte', 'Qué datos enviar por WhatsApp para recibir una respuesta rápida cuando compras para negocio, restaurante o reventa.', '
<h2>Comprar por mayor es más fácil si envías datos claros</h2>
<p>Cuando alguien consulta por mayor, normalmente necesita precio, cantidad, presentación, disponibilidad y forma de entrega. Si el mensaje llega incompleto, la respuesta se demora porque primero hay que pedir más información.</p>
<p>Para ayudarte más rápido, lo mejor es enviar desde el inicio qué producto necesitas, en qué cantidad, para cuándo y en qué zona deseas coordinar.</p>
<p style="background:#ecfdf5;border-left:4px solid #16a34a;padding:12px 14px;border-radius:10px;margin:16px 0;"><strong>Nota:</strong> La disponibilidad puede variar por temporada. Antes de comprar por cantidad, confirma stock y presentación por WhatsApp.</p>
<h2>Datos que debes enviar</h2>
<div style="overflow-x:auto;margin:16px 0;"><table style="width:100%;border-collapse:collapse;font-size:15px;"><thead><tr><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Dato</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Ejemplo recomendado</th></tr></thead><tbody><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Producto</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Paiche seco, hoja de bijao, pescado ahumado, cecina, frutas o harinas.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Cantidad</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">10 kg, 5 paquetes, 100 hojas, 20 unidades o cantidad aproximada.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Tipo de compra</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Por menor, por mayor, para restaurante, para reventa o para evento.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Zona de entrega</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Iquitos, distrito, referencia o punto de coordinación.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Fecha aproximada</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hoy, mañana, esta semana, antes de una fecha especial.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Observación</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Si necesitas una presentación específica, producto más seco, hojas grandes, etc.</td></tr></tbody></table></div>
<h2>Mensaje modelo para copiar</h2>
<blockquote style="border-left:4px solid #16a34a;background:#f0fdf4;padding:14px 16px;border-radius:10px;margin:16px 0;">Hola, quisiera consultar por <strong>paiche seco por mayor</strong>. Necesito aproximadamente <strong>10 kg</strong> para <strong>Iquitos</strong>, entrega esta semana. ¿Tienen disponibilidad y precio actualizado?</blockquote>
<h2>Productos que suelen consultarse por mayor</h2>
<div style="overflow-x:auto;margin:16px 0;"><table style="width:100%;border-collapse:collapse;font-size:15px;"><thead><tr><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Producto</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Uso frecuente</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Recomendación</th></tr></thead><tbody><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Paiche seco</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Restaurantes, hogares y eventos.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Confirmar peso, presentación y disponibilidad.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hojas de bijao</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Juanes, tamales y comidas tradicionales.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Comprar con anticipación en temporada alta.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hojas de plátano</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Preparaciones amplias, vapor y parrilla.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Indicar si se necesitan hojas grandes.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Ahumados</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Negocios de comida y consumo familiar.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Consultar si son para consumo rápido o almacenamiento.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Pescado seco variado</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Reventa y cocina tradicional.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Confirmar tipo de pescado y cantidad.</td></tr></tbody></table></div>
<div style="background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Checklist rápido</h3><ul style="margin-bottom:0;list-style:none;padding-left:0;"><li style="margin-bottom:8px;">✅ Definir producto y cantidad.</li><li style="margin-bottom:8px;">✅ Confirmar si es precio por mayor o menor.</li><li style="margin-bottom:8px;">✅ Indicar zona de entrega.</li><li style="margin-bottom:8px;">✅ Pedir confirmación de disponibilidad antes de cerrar.</li></ul></div>
<h2>Ventajas de consultar bien</h2>
<p>Un mensaje claro permite confirmar stock, evitar confusiones, coordinar mejor la entrega y responder con mayor precisión. También ayuda a separar productos cuando la disponibilidad es limitada.</p>
<div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Nivel recomendado</h3><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Respuesta más rápida</strong><span>95%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:95%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Menos confusiones</strong><span>90%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:90%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Mejor coordinación</strong><span>85%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:85%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Pedido sin datos</strong><span>25%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:25%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div></div>
<h2>Conclusión</h2>
<p>Comprar por mayor no tiene que ser complicado. Mientras más claro sea tu mensaje, más fácil será confirmar disponibilidad, precio y coordinación.</p>
<div style="background:#0f766e;color:#fff;padding:18px;border-radius:14px;margin-top:22px;"><h3 style="margin-top:0;color:#fff;">Consulta por WhatsApp</h3><p style="margin-bottom:0;">Escríbenos indicando producto, cantidad, zona y fecha aproximada. Te ayudamos a coordinar tu pedido por WhatsApp.</p></div>
', '/uploads/belen/blog/03-compras-por-mayor.jpg', 'PUBLISHED', '2026-05-28 20:30:00', '2026-05-28 20:30:00')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `summary` = VALUES(`summary`),
  `content` = VALUES(`content`),
  `cover_image_path` = VALUES(`cover_image_path`),
  `status` = VALUES(`status`),
  `published_at` = VALUES(`published_at`);

-- Article 4: Productos amazónicos para temporada de San Juan
INSERT INTO `blog_post` (`title`, `slug`, `summary`, `content`, `cover_image_path`, `status`, `created_at`, `published_at`) VALUES
('Productos amazónicos para temporada de San Juan', 'productos-amazonicos-para-temporada-de-san-juan', 'Ideas de productos que suelen tener alta demanda en temporada de San Juan y cómo pedir con anticipación.', '
<h2>San Juan mueve la cocina amazónica</h2>
<p>La temporada de San Juan es una de las fechas más importantes para los productos amazónicos. En esos días muchas familias, restaurantes y negocios buscan hojas, pescados, ahumados y otros insumos para preparar comidas tradicionales.</p>
<p>Por eso, si necesitas comprar para tu casa, negocio o evento, lo mejor es consultar disponibilidad con anticipación. Algunos productos pueden agotarse rápido o variar de precio según la demanda.</p>
<p style="background:#ecfdf5;border-left:4px solid #16a34a;padding:12px 14px;border-radius:10px;margin:16px 0;"><strong>Nota:</strong> La disponibilidad puede variar por temporada. Antes de comprar por cantidad, confirma stock y presentación por WhatsApp.</p>
<h2>Productos con mayor movimiento en temporada</h2>
<div style="overflow-x:auto;margin:16px 0;"><table style="width:100%;border-collapse:collapse;font-size:15px;"><thead><tr><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Producto</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Uso frecuente en temporada</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Recomendación</th></tr></thead><tbody><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hoja de bijao</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Juanes y comidas tradicionales.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Consultar paquetes con anticipación.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hoja de plátano</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Envolturas grandes, cocción al vapor y presentación.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Indicar tamaño o cantidad aproximada.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Paiche seco</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Platos típicos, consumo familiar y restaurantes.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Confirmar disponibilidad y presentación.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Pescados secos</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Cocina tradicional y pedidos por volumen.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Preguntar por variedad disponible.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Ahumados</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Complementos para platos y negocios de comida.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Comprar según fecha de uso.</td></tr></tbody></table></div>
<h2>¿Por qué pedir antes?</h2>
<ul><li>Te permite separar productos según disponibilidad.</li><li>Evita quedarte sin hojas o pescado en fechas fuertes.</li><li>Ayuda a coordinar mejor entrega o punto de recojo.</li><li>Permite comparar si necesitas por menor o por mayor.</li></ul>
<div style="background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Checklist rápido</h3><ul style="margin-bottom:0;list-style:none;padding-left:0;"><li style="margin-bottom:8px;">✅ Consulta mínimo unos días antes si es para negocio.</li><li style="margin-bottom:8px;">✅ Indica cantidad exacta o aproximada.</li><li style="margin-bottom:8px;">✅ Pregunta si el producto está disponible en la presentación que necesitas.</li><li style="margin-bottom:8px;">✅ Confirma fecha y punto de entrega.</li></ul></div>
<h2>Ideas para hogares y negocios</h2>
<div style="overflow-x:auto;margin:16px 0;"><table style="width:100%;border-collapse:collapse;font-size:15px;"><thead><tr><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Tipo de cliente</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Productos sugeridos</th></tr></thead><tbody><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hogar</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hojas de bijao, pescado seco, ahumados y frutas según disponibilidad.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Restaurante</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hojas por paquete, paiche seco, pescado seco variado y ahumados.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Bodega o reventa</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Productos secos, harinas, dulces y presentaciones de mayor duración.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Evento familiar</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Hojas, pescados y productos tradicionales según cantidad de invitados.</td></tr></tbody></table></div>
<div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Nivel recomendado</h3><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Hoja de bijao</strong><span>95%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:95%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Paiche seco</strong><span>90%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:90%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Pescado seco variado</strong><span>85%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:85%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Frutas amazónicas</strong><span>65%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:65%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div></div>
<h2>Conclusión</h2>
<p>La temporada de San Juan es una buena oportunidad para organizar tus compras con tiempo. Si necesitas productos para casa, restaurante o evento, consulta disponibilidad antes de la fecha para evitar apuros.</p>
<div style="background:#0f766e;color:#fff;padding:18px;border-radius:14px;margin-top:22px;"><h3 style="margin-top:0;color:#fff;">Consulta por WhatsApp</h3><p style="margin-bottom:0;">Para temporada de San Juan, escríbenos por WhatsApp con tu lista de productos y cantidad aproximada. Te confirmamos disponibilidad según stock.</p></div>
', '/uploads/belen/blog/04-temporada-san-juan.jpg', 'PUBLISHED', '2026-05-28 20:30:00', '2026-05-28 20:30:00')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `summary` = VALUES(`summary`),
  `content` = VALUES(`content`),
  `cover_image_path` = VALUES(`cover_image_path`),
  `status` = VALUES(`status`),
  `published_at` = VALUES(`published_at`);

-- Article 5: Diferencias entre pescado fresco, seco y ahumado
INSERT INTO `blog_post` (`title`, `slug`, `summary`, `content`, `cover_image_path`, `status`, `created_at`, `published_at`) VALUES
('Diferencias entre pescado fresco, seco y ahumado', 'diferencias-entre-pescado-fresco-seco-y-ahumado', 'Aprende cuándo conviene elegir pescado fresco, pescado seco o pescado ahumado según uso, sabor y conservación.', '
<h2>No todos los pescados se usan igual</h2>
<p>El pescado fresco, el pescado seco y el pescado ahumado tienen usos diferentes. Elegir bien depende de cuándo vas a cocinar, cuánto tiempo necesitas conservarlo y qué sabor buscas en la preparación.</p>
<p>Para consumo inmediato, el fresco suele ser una buena opción. Para guardar más tiempo o preparar platos con sabor más concentrado, el seco y el ahumado pueden ser más convenientes.</p>
<p style="background:#ecfdf5;border-left:4px solid #16a34a;padding:12px 14px;border-radius:10px;margin:16px 0;"><strong>Nota:</strong> La disponibilidad puede variar por temporada. Antes de comprar por cantidad, confirma stock y presentación por WhatsApp.</p>
<h2>Comparativa rápida</h2>
<div style="overflow-x:auto;margin:16px 0;"><table style="width:100%;border-collapse:collapse;font-size:15px;"><thead><tr><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Tipo de producto</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Sabor</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Conservación</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Uso recomendado</th></tr></thead><tbody><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Pescado fresco</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Natural y suave.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Requiere frío y consumo rápido.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Comidas del día, fritos, sudados, caldos o parrilla.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Pescado seco</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Más concentrado e intenso.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Dura más si se guarda seco y protegido.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Guisos, platos tradicionales y compras por cantidad.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Pescado ahumado</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Aroma marcado y sabor profundo.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Puede durar más, pero debe cuidarse de humedad.</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Platos con sabor fuerte, acompañamientos y recetas amazónicas.</td></tr></tbody></table></div>
<h2>¿Cuál conviene para cada caso?</h2>
<ul><li><strong>Para cocinar hoy:</strong> pescado fresco.</li><li><strong>Para guardar algunos días:</strong> pescado seco bien conservado.</li><li><strong>Para dar sabor intenso:</strong> pescado ahumado.</li><li><strong>Para negocio de comida:</strong> combinar fresco, seco y ahumado según menú.</li></ul>
<div style="background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Checklist rápido</h3><ul style="margin-bottom:0;list-style:none;padding-left:0;"><li style="margin-bottom:8px;">✅ Pregunta disponibilidad del día.</li><li style="margin-bottom:8px;">✅ Consulta presentación y peso aproximado.</li><li style="margin-bottom:8px;">✅ Elige fresco si vas a cocinar pronto.</li><li style="margin-bottom:8px;">✅ Elige seco o ahumado si necesitas más duración.</li></ul></div>
<h2>Qué revisar antes de comprar</h2>
<div style="overflow-x:auto;margin:16px 0;"><table style="width:100%;border-collapse:collapse;font-size:15px;"><thead><tr><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Punto de revisión</th><th style="border:1px solid #d1d5db;padding:10px;background:#166534;color:#fff;text-align:left;">Qué observar</th></tr></thead><tbody><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Olor</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Debe ser natural. Evita olores agrios o desagradables.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Color</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Debe verse estable y sin manchas extrañas.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Textura</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">En seco o ahumado debe sentirse firme, no pegajoso.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Humedad</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Evita productos con humedad excesiva si los quieres conservar.</td></tr><tr><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Presentación</td><td style="border:1px solid #d1d5db;padding:10px;vertical-align:top;">Consulta si viene entero, por piezas, por peso o por paquete.</td></tr></tbody></table></div>
<div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:14px;padding:16px;margin:16px 0;"><h3 style="margin-top:0;">Nivel recomendado</h3><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Consumo inmediato: fresco</strong><span>95%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:95%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Mayor duración: seco</strong><span>85%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:85%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Sabor intenso: ahumado</strong><span>90%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:90%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div><div style="margin:10px 0;"><div style="display:flex;justify-content:space-between;font-size:14px;"><strong>Guardar sin cuidado</strong><span>15%</span></div><div style="background:#e5e7eb;border-radius:999px;height:10px;"><div style="width:15%;height:10px;border-radius:999px;background:#16a34a;"></div></div></div></div>
<h2>Conclusión</h2>
<p>No hay una única mejor opción. El pescado fresco, seco y ahumado sirven para necesidades distintas. Lo importante es comprar según el uso que le darás, confirmar disponibilidad y conservarlo correctamente.</p>
<div style="background:#0f766e;color:#fff;padding:18px;border-radius:14px;margin-top:22px;"><h3 style="margin-top:0;color:#fff;">Consulta por WhatsApp</h3><p style="margin-bottom:0;">Consulta por WhatsApp qué pescado hay disponible hoy y qué presentación se acomoda mejor a tu hogar o negocio.</p></div>
', '/uploads/belen/blog/05-pescado-fresco-seco-ahumado.jpg', 'PUBLISHED', '2026-05-28 20:30:00', '2026-05-28 20:30:00')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `summary` = VALUES(`summary`),
  `content` = VALUES(`content`),
  `cover_image_path` = VALUES(`cover_image_path`),
  `status` = VALUES(`status`),
  `published_at` = VALUES(`published_at`);

-- Validation
SELECT `id`, `title`, `slug`, `cover_image_path`, `status` FROM `blog_post` WHERE `slug` IN ('como-conservar-paiche-seco-y-pescado-ahumado','hoja-de-bijao-y-hoja-de-platano-cuando-usar-cada-una','como-consultar-precios-por-mayor-sin-complicarte','productos-amazonicos-para-temporada-de-san-juan','diferencias-entre-pescado-fresco-seco-y-ahumado') ORDER BY `published_at` DESC;