-- Bootstrap inicial generado desde Super Admin para: Restaurante El Buen Sabor
-- Ejecutar este script después de copiar la estructura base.

USE `restaurante_buen_sabor`;

INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('platform.name', 'Restaurante El Buen Sabor', 'string', 'platform', 'Nombre comercial del negocio') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('platform.tagline', 'Carta, pedidos y delivery para tu restaurante.', 'string', 'platform', 'Lema inicial del negocio') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('public.whatsapp.number', '+51999999999', 'string', 'public_site', 'WhatsApp comercial del negocio') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('public.topbar.phone', '+51999999999', 'string', 'public_site', 'Teléfono principal del negocio') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('public.topbar.location', 'Iquitos', 'string', 'public_site', 'Ciudad o zona de atención') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('public.theme.primary_color', '#fd7e14', 'string', 'public_site', 'Color principal del portal público') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('public.nav.home_label', 'Inicio', 'string', 'public_site', 'Etiqueta de inicio') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('public.nav.catalog_label', 'Carta', 'string', 'public_site', 'Etiqueta de catálogo o carta') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('public.nav.access_label', 'Acceso colaboradores', 'string', 'public_site', 'Etiqueta de login interno') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);

-- Módulos activos según la plantilla seleccionada.
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.academy.enabled', 'false', 'boolean', 'system_modules', 'Módulo Academia / cursos') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.clients.enabled', 'true', 'boolean', 'system_modules', 'Módulo Clientes y cartera') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.sales.enabled', 'true', 'boolean', 'system_modules', 'Módulo Ventas y pedidos') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.ecommerce_filters.enabled', 'false', 'boolean', 'system_modules', 'Módulo Catálogo tipo Temu') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.product_importer.enabled', 'false', 'boolean', 'system_modules', 'Módulo Importador de productos') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.income.enabled', 'true', 'boolean', 'system_modules', 'Módulo Ingresos y cobranza') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.expenses.enabled', 'true', 'boolean', 'system_modules', 'Módulo Egresos y compras') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.accounting.enabled', 'false', 'boolean', 'system_modules', 'Módulo Contabilidad básica') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.products.enabled', 'true', 'boolean', 'system_modules', 'Módulo Productos / platos / servicios') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.warehouse.enabled', 'true', 'boolean', 'system_modules', 'Módulo Almacén / stock') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.supplies.enabled', 'true', 'boolean', 'system_modules', 'Módulo Insumos') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.marketing.enabled', 'true', 'boolean', 'system_modules', 'Módulo Marketing y campañas') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.blog.enabled', 'false', 'boolean', 'system_modules', 'Módulo Blog / contenido') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.production.enabled', 'false', 'boolean', 'system_modules', 'Módulo Producción') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.delivery.enabled', 'true', 'boolean', 'system_modules', 'Módulo Reparto inteligente') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.reorder.enabled', 'false', 'boolean', 'system_modules', 'Módulo Recompras / reposición') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.restaurant.enabled', 'true', 'boolean', 'system_modules', 'Módulo Restaurante / carta digital, mesas, comandas y cocina') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.public_catalog.enabled', 'true', 'boolean', 'system_modules', 'Módulo Catálogo público') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.dashboard.enabled', 'true', 'boolean', 'system_modules', 'Módulo Inicio administrativo') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.business_overview.enabled', 'true', 'boolean', 'system_modules', 'Módulo Dashboard gerencial') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.restaurant_tables.enabled', 'true', 'boolean', 'system_modules', 'Módulo Mesas y salón') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.restaurant_kitchen.enabled', 'true', 'boolean', 'system_modules', 'Módulo Comandas y cocina') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.restaurant_menu_qr.enabled', 'true', 'boolean', 'system_modules', 'Módulo Carta digital QR') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.restaurant_recipes.enabled', 'true', 'boolean', 'system_modules', 'Módulo Recetas y costeo') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);
INSERT INTO platform_setting (`variable`, `value`, `type`, `category`, `description`) VALUES ('module.hr.enabled', 'true', 'boolean', 'system_modules', 'Módulo Recursos humanos') ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `type` = VALUES(`type`), `category` = VALUES(`category`), `description` = VALUES(`description`);

-- Usuario administrador inicial sugerido.
-- Recomendado: crear desde la pantalla Usuarios del sistema destino o copiar usuarios demo desde la base modelo.
-- Usuario sugerido: admin_demo / clave temporal: Demo12345
-- Luego cambiar la clave y asignar permisos según el rubro.

-- Datos demo: habilitados.
-- Ejecutar luego el script demo específico de la plantilla cuando exista.
